paths:
  /api/productos/gets:
    get:
      summary: Obtiene todos los productos y puede variar con querys
      tags:
        - Product
      responses:
        "200":
          description: productos obtenidos correctamente
          content:
            application/json:
              schema:
                type: array  
        "500":  
          description: error interno del server, usualmente por query defectuosa. 
  /api/productos/get:
    get:
      summary: Obtiene todos los productos
      tags:
        - Product
      responses:
        "200":
          description: productos obtenidos correctamente
          content:
            application/json:
              schema:
                type: array  
        "500":  
          description: error interno del server, usualmente por query defectuosa. 
  /api/productos/{Pid}:
    get:
      summary: Obtiene todos los productos
      tags:
        - Product
      parameters: 
        - name: Pid
          in: path
          required: true
          description: El id del producto
          schema: 
            type: string  
      responses:
        "200":
          description: productos obtenidos correctamente
          content:
            application/json:
              schema:
                type: object  
        "500":  
          description: error interno del server, usualmente por query defectuosa. 
  /api/productos/:
    post:
      summary: Agrega un producto 
      tags: 
        - Product
      responses: 
        "200":
          description: El producto se ha agregado correctamente
          content:
            application/json:
              schema:
                type: object
        "500":
          description: Error interno del servidor
  /api/productos/{:Pid}:        
    put:
      summary: Update a un producto
      tags: 
        - Product
      parameters: 
        - name: Pid
          in: path
          required: true
          description: El id del producto
          schema: 
            type: string
      responses: 
        "200":
          description: El producto se ha Actualizado correctamente
          schema: 
            type: string
        "500":
          description: Error interno del servidor
  /api/products/{:Pid}:
    delete:
      summary: borrar un producto 
      tags: 
        - Product
      parameters: 
        - name: Pid
          in: path
          required: true
          description: El id del producto
          schema: 
            type: string
      responses: 
        "200":
          description: El producto se ha borrado correctamente
          schema: 
            type: string
        "500":
          description: Error interno del servidor        
  